% get_sbe_39.m
% process ascii file generated by Seabird software
% Requirements:
%   before calling, set the "infile" input file name :
%      e.g. infile ='NTASII_SBE39SN0681.asc'
%   You must have access to mon_str2num (see end) 
% uses textscan for speed
% vers 2015/02/27 save header lines in headers cell

meta.history.decode.program = mfilename('fullpath'); 
meta.history.decode.program_version = '2010/10/27 n.galbraith';
infid=fopen([infile '.asc'],'rt');
fprintf('opening %s\n', infile);
if infid
    fprintf('get_sbe_39 opened %s\n', infile);
    % count header lines:
    nlines = 1;
    nhdrlines=0;
    nheadkeep=0;
    while(1)
        inline=fgets(infid);    
        if inline == -1,
            break;
        end
        % stash some header lines
        % * Software Version 1.59
        % * System UpLoad Time = Feb 23 2015 18:41:01
        % * SBE 39 V 3.1b   SERIAL NO. 5270    23 Feb 2015  18:41:42
        % * SBE39 V 3.1b   05270
        % * temperature:  01-feb-13
        % *     TA0 = -1.267390e-04
        % *     TA1 = 3.085584e-04
        % *     TA2 = -4.495387e-06
        % *     TA3 = 2.017697e-07
        % 123456789 123456789 1234
        if length(inline) > 19 && nhdrlines == 0
                    nheadkeep=nheadkeep+1;
                    headers{1,nheadkeep}=inline;
        end
        if strfind(inline,'start sample number')
            nhdrlines=nlines;
            
        end
        nlines=nlines + 1;
    end
    fprintf('read %d lines, %d header lines, kept %d ',nlines, nhdrlines,nheadkeep);
    
    % move file pointer back to beginning
    fseek(infid,0,'bof');
    % load the data into a cell array
    sdata=textscan(infid,'%f, %.0f %3c %.0f, %.0f:%.0f:%.0f','headerlines', nhdrlines);
    fclose(infid);

    vnames = {'atmp', 'day', 'monstr', 'year','hour','minute','second'};
    for ii=1:length(vnames)
        vname=vnames{ii}; mydat=sdata{ii};
        eval([ vname ' = mydat(:,:);' ]);
    end

    % covert monthstrings to month numbers
    mon = mon_str2num(monstr);
    % get matlab date
    mday= datenum(year,mon,day, hour, minute,second);
    year=year(1);
    yday=mday-datenum(year,1,0);
end
fprintf('read %d records\n',length(mday));
save([DATADIR 'processed/' sbe39ATfiles{i}],'atmp','mday','meta');

